### ISSUE TITLE
Secure mqtt clients creation / removes in dhcp/network with Locks

### ISSUE THREAD

**Issue by bibi21000** [bibi21000/janitoo#6]
A cool case study is the janitoo_tkinter application ( secondary node ).

**Comment by bibi21000** [comment]
DEBUG [janitoo.mqtt] [MQTTClient] - Stop the mqtt client
ERROR [janitoo.dhcp] Catched exception
Traceback (most recent call last):
  File "/home/sebastien/devel/janitoo/janitoo/src/janitoo/dhcp.py", line 1075, in stop_resolv_heartbeat
    self.resolv_heartbeat_mqttc.stop()
AttributeError: 'NoneType' object has no attribute 'stop'
ERROR [janitoo.dhcp] Catched exception
Traceback (most recent call last):
  File "/home/sebastien/devel/janitoo/janitoo/src/janitoo/dhcp.py", line 1075, in stop_resolv_heartbeat
    self.resolv_heartbeat_mqttc.stop()
AttributeError: 'NoneType' object has no attribute 'stop'

**Comment by bibi21000** [comment]
Done but do not the job.

Add lock for timers too

**Comment by bibi21000** [comment]
```
sebastien@SATELLITE-C70D-A:~/devel/janitoo/janitoo_tkinter$ jnt_tkui 
Exception in thread Thread-41:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 1082, in run
    self.function(*self.args, **self.kwargs)
  File "/home/sebastien/devel/janitoo/janitoo/src/janitoo/dhcp.py", line 764, in finish_broadcast_users_discover
    self.fsm_network_next()
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 222, in trigger
    return self.machine.process(f)
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 526, in process
    return trigger()
  File "build/bdist.linux-x86_64/egg/transitions/core.py", line 242, in _trigger
    raise MachineError(msg)
MachineError: "Can't trigger event fsm_network_next from state STARTED!"


```
